let EN = {ALREADYACCOUNT: " Already have account?",
ATC: "ADD TO CART",
AccountASuccess: "Account activated successfully!",
ActivateAccount: "Activate Account",
Add: "Add",
AddNew: "Add New",
AddReview: "Add Your Review",
Addon: "Add on",
Address: "Address",
AddressLower: "address",
Addresses: "Addresses",
All: "All Ratings",
Applycoupon: "Apply coupon",
BasedOn: "Based on",
BillingAddress: "Billing Address",
CONTINUESHOPPING: "Continue shopping",
Cancel: "Cancel",
Checkout: "Checkout",
Completed: "Completed",
ConfirmEmail: "Your order confirmation has been emailed to ",
Country: "Country / Region",
Couponcode: "Coupon code",
DONTHAVEACCOUNT: "Don't have account?",
DeleteAddress: "Delete address",
DeleteAddressConfrim: "Are you sure want to delete this address",
DeliveryNote: "DELIVERY NOTE",
DeliveryNotePH: "Please enter delivery note",
Discount: "Discount",
ENTER_EMAIL: "Enter email",
EditProfile: "Edit Profile",
Email: "Email",
Emptycart: "Your cart is currently empty.",
EnterPwd: "Enter Password",
Entername: "Enter account name",
FBR: "Filter by Ratings",
ForgotPwd: "Forgot Password?",
HOUSE: "House number and street name",
HasbeenRecieved: " has been received",
LOGOUTMSG: "Are you sure want to logout?",
Latestfirst: "Latest first",
LogInCreate: "Log in or create a new account",
Logout: "Logout",
MyAddresses: "My Addresses",
MyOrders: "My Orders",
MyTickets: "My Tickets",
Name: "Name",
NewShipAdd: "New Shipping Address",
No: "No",
NoOrder: "No orders",
NotAvail: "Not Available",
Olderfirst: "Older first",
OrderDetails: "Your order Details #",
OrderNo: "Order No",
OrderStatus: "Order Status",
OrderedOn: "Ordered on",
Orders: "Orders",
Outofstock: "Out of Stock",
OverExp: "How was your overall experience?",
PDD: "Probable Delivery Date",
PNF: "Page Not Found",
PaymentStatus: "Payment Status",
Pending: "Pending",
Phone: "Phone",
Phonenumber: "Phone number",
Placeorder: "Place order",
Price: "Price",
Proceedcheckout: "Proceed to checkout",
Processing: "Processing",
Product: "Product",
Productsuccess: " Product added to cart successfully",
Quantity: "Quantity",
RETUNRNSHOP: "RETURN TO SHOP",
Rating: "Rating",
RecipientName: "Recipient Name",
Removecoupon: "Remove coupon",
ResetPwd: "RESET PASSWORD",
RetryPayment: "Retry Payment",
Reviews: "Reviews",
SIGN_IN: "SIGN IN",
SIGN_INTOCHECKOUT: "Please Sign In to Checkout & Track your Order",
SIGN_UP: "Sign Up",
SYexperience: "Share your experience",
Save: "Save",
SaveChanges: "Save Changes",
Savings: "savings",
Search: "Search",
SearchPH: "Search other experiences here",
SelectaSize: "Select a Size",
Selectacountry: "Select a country",
Selectaddress: "Select address",
Send: "Send",
Shipping: "Shipping",
ShippingAddress: "Shipping Address",
ShippingAddressDiff: "Ship to different address (optional)",
ShippingCost: "Shipping Cost",
ShippingDetails: "Shipping Details",
ShopNow: "Shop Now",
Sort: "Sort",
State: "State",
Streetaddress: "Street address",
Submit: "Submit",
Subtotal: "Subtotal",
SureDeactivate: "Are you sure you want to deactivate account?",
TOWN: "Town / City",
TYYO: "Thank you. Your order #",
Thankyou: " Thank you. Your order has been received",
Tickets: "Tickets",
Total: "Total",
Update: "Update",
Yes: "Yes",
YourDetails: "Your Details",
Yourorder: "Your order",
ZIP: "Postcode / ZIP",

};

export { EN };
